server:
  port: 8088
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hp_wenxue
    username: root
    password: lwl123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    encoding: UTF-8
    cache: false
#    mode: HTML5
#    prefix: classpath:/templates/
#    suffix: .html
       


# 首次启动项目可以将ddl-auto 改为 create ,将会自动创建表结构
# 数据库需要手动创建好